# Generated by Django 4.2.6 on 2023-10-31 10:42

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(default=1, max_length=254, validators=[account.validators.validate_email], verbose_name='آدرس ایمیل'),
            preserve_default=False,
        ),
    ]
