# Generated by Django 4.2.6 on 2023-10-31 11:09

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_company_name_alter_otp_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='landline_phone',
            field=models.CharField(blank=True, help_text='ضروری', max_length=15, null=True, unique=True, validators=[account.validators.validate_landline_phone], verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
