# Generated by Django 4.2.6 on 2023-11-26 18:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='ضروری', max_length=100, verbose_name='کتگوری')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
            ],
            options={
                'verbose_name': 'کتگوری',
                'verbose_name_plural': 'کتگوری ها',
            },
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ضروری', max_length=50, verbose_name='تیتر')),
                ('weblog_preview', models.CharField(help_text='ضروری', max_length=200, verbose_name='درباره مقاله')),
                ('image', models.ImageField(help_text='ضروری', upload_to='weblog/weblog/images', verbose_name='تصویر')),
                ('body', ckeditor.fields.RichTextField(help_text='ضروری', max_length=50000, unique=True, verbose_name='بدنه')),
                ('is_allowed', models.BooleanField(default=True, help_text='ضروری', verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('actual_jalali_date', models.CharField(blank=True, help_text='ضروری', max_length=100, null=True, verbose_name='تاریخ جلالی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ (متن داخل URL)')),
                ('author', models.ForeignKey(help_text='ضروری', on_delete=django.db.models.deletion.CASCADE, related_name='weblogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categories', models.ManyToManyField(help_text='ضروری', related_name='weblogs', to='weblog.category', verbose_name='کتگوری ها')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
