# Generated by Django 4.2.6 on 2023-11-02 17:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ('-created_at',), 'verbose_name': 'آزمایشگاه', 'verbose_name_plural': 'آزمایشگاه ها'},
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='about_product',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='summary',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='body',
            field=ckeditor.fields.RichTextField(default=1, help_text='ضروری', max_length=50000, unique=True, verbose_name='بدنه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='date',
            field=models.CharField(default=1, help_text='ضروری', max_length=100, verbose_name='تاریخ ساخت سابقه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='financial_value',
            field=models.CharField(default=1, help_text='ضروری', max_length=50, verbose_name='ارزش مالی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_1',
            field=models.ImageField(default=1, help_text='ضروری', upload_to='laboratory/laboratory/images', verbose_name='تصویر 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_2',
            field=models.ImageField(default=1, help_text='ضروری', upload_to='laboratory/laboratory/images', verbose_name='تصویر 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_3',
            field=models.ImageField(default=1, help_text='ضروری', upload_to='laboratory/laboratory/images', verbose_name='تصویر 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_4',
            field=models.ImageField(default=1, help_text='ضروری', upload_to='laboratory/laboratory/images', verbose_name='تصویر 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 5'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 6'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 7'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 8'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='location',
            field=models.CharField(default=1, help_text='ضروری', max_length=100, verbose_name='لوکیشن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='record_preview',
            field=models.CharField(default=1, help_text='ضروری', max_length=200, verbose_name='درباره سابقه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='title',
            field=models.CharField(default=11, help_text='ضروری', max_length=50, verbose_name='تیتر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ (متن داخل URL)'),
        ),
    ]
