# Generated by Django 4.2.6 on 2023-11-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_category_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='category',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory', verbose_name='والد'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
