# Generated by Django 4.2.6 on 2023-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_remove_laboratory_category_laboratory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='child',
            field=models.BooleanField(default=False, help_text='ضروری', verbose_name='فرزند دارد'),
        ),
    ]
