# Generated by Django 4.2.6 on 2023-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_laboratory_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='child',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='has_child',
            field=models.BooleanField(default=False, help_text='ضروری', verbose_name='فرزند دارد؟'),
        ),
    ]
