# Generated by Django 4.2.6 on 2023-11-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_remove_laboratory_child_laboratory_has_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='parent',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='has_parent',
            field=models.BooleanField(default=False, help_text='ضروری', verbose_name='والد دارد؟'),
        ),
    ]
