# Generated by Django 4.2.6 on 2023-11-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_category_remove_laboratory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='has_child',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='has_parent',
        ),
    ]
