# Generated by Django 4.2.6 on 2023-11-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_alter_category_options_remove_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='ضروری', max_length=150, verbose_name='اسلاگ (متن داخل URL)'),
        ),
    ]
