# Generated by Django 4.2.6 on 2023-11-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='image_8',
        ),
    ]
