# Generated by Django 4.2.6 on 2023-11-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_remove_laboratory_image_7_remove_laboratory_image_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='category',
            field=models.ForeignKey(help_text='ضروری', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='laboratory.category', verbose_name='دسته بندی'),
        ),
    ]
