# Generated by Django 4.2.6 on 2023-11-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_alter_laboratory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='laboratory.category'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='category',
            field=models.ForeignKey(help_text='ضروری', on_delete=django.db.models.deletion.CASCADE, to='laboratory.category', verbose_name='دسته بندی'),
        ),
    ]
