# Generated by Django 4.2.6 on 2023-11-14 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='about_this_lab',
            field=ckeditor.fields.RichTextField(default=1, help_text='ضروری', max_length=1000, verbose_name='درباره این آزمایشگاه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 2'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 3'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='laboratory/laboratory/images', verbose_name='تصویر 4'),
        ),
    ]
