# Generated by Django 4.2.6 on 2023-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='work_time',
            field=models.CharField(default=1, help_text='ضروری', max_length=200, verbose_name='ساعت کاری'),
            preserve_default=False,
        ),
    ]
