# Generated by Django 4.2.6 on 2023-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactinfo_work_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='landline_phone',
            new_name='landline_phone_1',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='landline_phone_2',
            field=models.CharField(default=1, help_text='ضروری', max_length=15, unique=True, verbose_name='شماره تلفن ثابت'),
            preserve_default=False,
        ),
    ]
