# Generated by Django 4.2.6 on 2023-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_rename_landline_phone_contactinfo_landline_phone_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='landline_phone_1',
            field=models.CharField(help_text='ضروری', max_length=150, unique=True, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='landline_phone_2',
            field=models.CharField(help_text='ضروری', max_length=150, unique=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
