# Generated by Django 4.2.6 on 2023-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_alter_contactinfo_landline_phone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='eitta',
            field=models.CharField(default=1, help_text='ضروری', max_length=11, verbose_name='شماره تلفن همراه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='telegram',
            field=models.CharField(default=1, help_text='ضروری', max_length=11, verbose_name='شماره تلفن همراه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(default=1, help_text='ضروری', max_length=11, verbose_name='شماره تلفن همراه'),
            preserve_default=False,
        ),
    ]
