# Generated by Django 4.2.6 on 2023-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_alter_contactinfo_eitta_alter_contactinfo_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='eitta',
            field=models.CharField(help_text='ضروری', max_length=150, verbose_name='ایتا'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile_phone',
            field=models.CharField(help_text='ضروری', max_length=150, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram',
            field=models.CharField(help_text='ضروری', max_length=150, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(help_text='ضروری', max_length=150, verbose_name='واتس اپ'),
        ),
    ]
