# Generated by Django 4.2.6 on 2023-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalwebsiteideaimage',
            name='title',
            field=models.CharField(default=1, help_text='ضروری', max_length=100, verbose_name='تیتر (نمایش داده نمی شود.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='about',
            field=models.TextField(help_text='ضروری', max_length=1000, verbose_name='درباره'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='ضروری', max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='ضروری', max_length=100, verbose_name='نقش'),
        ),
    ]
