# Generated by Django 4.2.6 on 2023-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ضروری', max_length=75, unique=True, verbose_name='تیتر')),
                ('body', models.TextField(help_text='ضروری', max_length=300, unique=True, verbose_name='بدنه')),
            ],
            options={
                'verbose_name': 'درباره',
                'verbose_name_plural': 'درباره ها',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='ضروری', max_length=500, unique=True, verbose_name='سوال')),
                ('answer', models.TextField(help_text='ضروری', max_length=1500, unique=True, verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
