# Generated by Django 4.2.6 on 2023-10-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(help_text='ضروری', max_length=300, unique=True, verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='ضروری', max_length=50, unique=True, verbose_name='تیتر'),
        ),
    ]
