# Generated by Django 4.2.6 on 2023-10-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_body_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(help_text='ضروری', max_length=75, unique=True, verbose_name='تیتر'),
        ),
    ]
