# Generated by Django 4.2.6 on 2023-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiding',
            name='tiding_preview',
            field=models.CharField(help_text='ضروری', max_length=200, verbose_name='درباره خبر'),
        ),
    ]
