# Generated by Django 4.2.6 on 2023-11-26 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='ضروری', max_length=100, verbose_name='کتگوری')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
            ],
            options={
                'verbose_name': 'کتگوری',
                'verbose_name_plural': 'کتگوری ها',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ضروری', max_length=50, verbose_name='تیتر')),
                ('record_preview', models.CharField(help_text='ضروری', max_length=200, verbose_name='درباره سابقه')),
                ('image_1', models.ImageField(help_text='ضروری', upload_to='new/new/images', verbose_name='تصویر 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 5')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 6')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 7')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 8')),
                ('body', ckeditor.fields.RichTextField(help_text='ضروری', max_length=50000, unique=True, verbose_name='بدنه')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ (متن داخل URL)')),
                ('categories', models.ManyToManyField(help_text='ضروری', related_name='weblogs', to='record.category', verbose_name='کتگوری ها')),
            ],
            options={
                'verbose_name': 'سابقه',
                'verbose_name_plural': 'سوابق',
                'ordering': ('-created_at',),
            },
        ),
    ]
