# Generated by Django 4.2.6 on 2023-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-created_at',), 'verbose_name': 'سابقه', 'verbose_name_plural': 'سوابق'},
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(help_text='ضروری', max_length=100, verbose_name='تاریخ ساخت سابقه'),
        ),
    ]
