# Generated by Django 4.2.6 on 2023-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_record_options_alter_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='financial_value',
        ),
        migrations.RemoveField(
            model_name='record',
            name='location',
        ),
        migrations.AlterField(
            model_name='record',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='new/new/images', verbose_name='تصویر 4'),
        ),
    ]
